spring:
  application:
    name: geteway
  cloud:
    bus:
      enabled: true
      trace:
        enabled: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  redis:
    host: localhost
    port: 6379
    password: 12345
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh
zuul:
  #全部服务忽略敏感头（全部服务都可以传递cookie）
  sensitive-headers: 
  routes:
    myProduct:
      path: /myProduct/**
      serviceId: product
      sensitiveHeaders:
  #排除某些路由
#  ignored-patterns:
#    - /**/product/listForOrder
 
