spring:
  application:
    name: order
  datasource:
    username: root
    password: $RF5tg6yh
    url: jdbc:mysql://localhost:3306/springcloud_sell?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false
  cloud:
    stream:
      bindings:
        MyMessage:
          group: order
          content-type: application/json
    bus:
      enabled: true
      trace:
        enabled: true
  zipkin:
    base-url: http://localhost:9411
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
#  redis:
#    host: localhost
#    port: 6379

# management:
#   endpoints:
#     web:
#       exposure:
#         include: bus-refresh
management:
  endpoints:
    web:
      exposure:
        include: "*"
      cors:
        allowed-origins: "*"
        allowed-methods: "*"


# server:
#   port: 8083
env: dev4
