management:
  endpoints:
    web:
      exposure:
        include: bus-refresh
spring:
  application:
    name: product
  cloud:
    bus:
      enabled: true
      trace:
        enabled: true
  datasource:
    password: $RF5tg6yh
    url: jdbc:mysql://localhost:3306/springcloud_sell?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false
    username: root
  rabbitmq:
    host: localhost
    password: guest
    port: 5672
    username: guest
